### PR TITLE
Closes #179 improve error messaging in `alias_as_fmt_fn()`

### LINKED ISSUE #179: Improve error message in `alias_as_fmt_fn()`
We're returning this error when the formatting function is not valid

```r
cli::cli_abort("Formatting functions/aliases must be a function, a non-negative integer, or a formatting string, e.g. {.val xx.x}.", call = call)
```

But this would be better if we referenced the statistic and the variable, so the user knows which functions are incorrect.

### PR DESCRIPTION
**Pull request by zdz2101**
What changes are proposed in this pull request?

Updated apply_fmt_fn() and its underlying functions to include variable name and statistic for errors with regards to formatting function

Reference GitHub issue associated with pull request. e.g., 'closes #'
closes #179

--------------------------------------------------------------------------------

Pre-review Checklist (if item does not apply, mark is as complete)
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [ ] If a bug was fixed, a unit test was added.
- [ ] Code coverage is suitable for any new functions/features (generally, 100% coverage for new code): `devtools::test_coverage()`
- [ ] Request a reviewer

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`

When the branch is ready to be merged:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cards (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge" or "Rebase and merge".

### CODE REVIEW

File: R/apply_fmt_fn.R [hunk 1]
```diff
@@ -89,7 +89,11 @@ alias_as_fmt_fn <- function(x, call = parent.frame()) {
     return(label_cards(digits = decimal_n, scale = scale, width = width))
   }
 
-  cli::cli_abort("Formatting functions/aliases must be a function, a non-negative integer, or a formatting string, e.g. {.val xx.x}.", call = call)
+  cli::cli_abort(
```
Comment (zdz2101) [inline R/apply_fmt_fn.R:92]: @ddsjoberg is the intention here to actually error out or to pass it into the error argument as well when running `apply_fmt_fn()`

File: R/apply_fmt_fn.R [hunk 2]
```diff
@@ -71,7 +71,7 @@ alias_as_fmt_fn <- function(x, call = parent.frame()) {
     return(label_cards(digits = as.integer(x)))
   }
   if (is_string(x)) {
-    .check_fmt_string(x, call = call)
+    .check_fmt_string(x, call = call) # .check_fmt_string() does have different messaging than the cli_abort() below was that intended?
```
Comment (zdz2101) [inline R/apply_fmt_fn.R:74]: Because `apply_fmt_fn()` is a wrapper for `alias_as_fmt_fn()` which contains `.check_fmt_string()` was the intention to have two separate error messages intentional?

File: tests/testthat/_snaps/apply_fmt_fn.md [hunk 3]
```diff
@@ -24,7 +24,7 @@
       Error in `dplyr::mutate()`:
       i In argument: `stat_fmt = map2(...)`.
       Caused by error:
-      ! Formatting functions/aliases must be a function, a non-negative integer, or a formatting string, e.g. "xx.x".
+      ! The value -1 supplied for `fmt_fn` cannot be applied to `stat`. Formatting functions/aliases must be a function, a non-negative integer, or a formatting string, e.g. "xx.x".
```
Comment (zdz2101) [inline tests/testthat/_snaps/apply_fmt_fn.md:27]: Also what extent are we trying to help the user in terms of the messaging?

**Review by zdz2101 — COMMENTED** [review]
@ddsjoberg couple questions about how to proceed

File: tests/testthat/_snaps/apply_fmt_fn.md [hunk 4]
```diff
@@ -12,19 +12,19 @@
       apply_fmt_fn(dplyr::mutate(ard_fmt_checks, fmt_fn = list("xoxo", "xoxo")))
     Condition
       Error in `dplyr::mutate()`:
-      i In argument: `stat_fmt = map2(...)`.
+      i In argument: `stat_fmt = pmap(...)`.
       Caused by error:
-      ! The format "xoxo" is not valid.
+      ! The format "xoxo" for `fmt_fn` is not valid for the value 20.090625 for the statistic "mean". String must begin with 'x' and only consist of x's, a single period or none, and may end with a percent symbol.
```
Comment (zdz2101) [inline tests/testthat/_snaps/apply_fmt_fn.md:17]: @ddsjoberg is something like this and the example right below what you had in mind?

File: tests/testthat/test-apply_fmt_fn.R [hunk 5]
```diff
@@ -90,7 +90,7 @@ test_that("apply_fmt_fn() error messaging", {
   expect_snapshot(
     ard_fmt_checks |>
       dplyr::mutate(
-        fmt_fn = list(-1L, -1L)
+        fmt_fn = list(1L, -1L)
```
Comment (zdz2101) [inline tests/testthat/test-apply_fmt_fn.R:93]: If there are multiple bad formats, assuming we can only collect first error right?

File: R/apply_fmt_fn.R [hunk 6]
```diff
@@ -54,6 +57,8 @@ apply_fmt_fn <- function(x) {
 #'
 #' @param x (`integer`, `string`, or `function`)\cr
 #'   a non-negative integer, string alias, or function
+#' @param stat the statistic that is to be formatted
+#' @param stat_name the name of the statistic that is to be formatted
```
Comment (edelarua) [inline R/apply_fmt_fn.R:61]: Add parameter types to documentation
```suggestion
#' @param stat (`numeric`)\cr the value of the statistic that is to be formatted
#' @param stat_name (`character`)\cr the name of the statistic that is to be formatted
```

File: R/apply_fmt_fn.R [hunk 7]
```diff
@@ -151,6 +162,8 @@ label_cards <- function(digits = 1, scale = 1, width = NULL) {
 #'
 #' @param x (`string`)\cr
 #'   string to check
+#' @param stat the statistic that is to be formatted
+#' @param stat_name the name of the statistic that is to be formatted
```
Comment (edelarua) [inline R/apply_fmt_fn.R:166]: Add parameter types again
```suggestion
#' @param stat (`numeric`)\cr the value of the statistic that is to be formatted
#' @param stat_name (`character`)\cr the name of the statistic that is to be formatted
```

**Review by edelarua — COMMENTED** [review]
Looks good!! Functions are working well for me, just a suggestion to clarify the parameter descriptions.

**Comment by ddsjoberg** [comment]
Thanks @zdz2101 ! Instead of printing the stat value, let's print the variable name and the stat_name?

**Comment by zdz2101** [comment]
> Thanks @zdz2101 ! Instead of printing the stat value, let's print the variable name and the stat_name?

@ddsjoberg updated!

**Comment by zdz2101** [comment]
@ddsjoberg merge conflicts and the caller stuff implemented from @edelarua PR is included now!

**Review by ddsjoberg — APPROVED** [review]
Thank you @zdz2101 !!! These messages look great!
